name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.8, 3.9, '3.10', '3.11']

    container:
      image: python:${{ matrix.python-version }}-slim

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          rm poetry.lock
          pipx install poetry
          poetry env use system
          poetry install --no-root
      - name: Test with pytest
        run: |
          poetry run pytest
